services:
  prometheus:
    restart: always
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
  node-exporter:
    restart: always
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - 9100:9100
  ping-exporter:
    restart: always
    image: czerwonk/ping_exporter
    ports:
      - "9427:9427"
    volumes:
      - ./ping-exporter.yml:/config/config.yml:ro
    cap_add:
      - NET_RAW

volumes:
  grafana-data: {}
  prometheus-data: {}

networks:
  default:
    enable_ipv6: true
