# Scrape node-exporter and blackbox-exporter metrics

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: 'blackbox-https'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - https://google.com
          - https://github.com
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [ icmp ]
    static_configs:
      - targets:
          - google.com
          - github.com
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: [ 'blackbox-exporter:9115' ]
  - job_name: "ping-exporter"
    static_configs:
      - targets: [ "ping-exporter:9427" ]